config/routes.rb
Rails.application.routes.draw do
  get 'main/index'

  get 'main/admin'

  get 'main/search'

  post 'main/query'

  get 'main/result'

  get 'main/user_result'

  devise_for :users

   root 'main#index'

end

app/models/query.rb
class Query < ActiveRecord::Base
  belongs_to :user, :foreign_key => :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :queries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # This is a test.
  protect_from_forgery with: :exception

end

app/controllers/cookies_controller.rb
class CookiesController < ApplicationController

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
    if user_signed_in?
      session[:current_user_id] = current_user.id
      @last = Query.where(:user_id => current_user.id).limit(5).order('created_at desc')
    else
      session[:current_user_id] = nil
      @last = nil
    end
  end

  def admin
  end

  def search
  end

  def query

    if user_signed_in?

      search = Query.new
      search.created_at = DateTime.now
      search.search_query = params[:query][:keyword]
      search.query_type = params[:query][:result_type]
      search.user_id = current_user.id
      search.search_limit = params[:query][:count].present? ? params[:query][:count] : 0
      if params[:query][:search_date].present?
        search.search_date = Date.strptime(params[:query][:search_date], '%m/%d/%Y').strftime("%Y-%m-%d")
      end
      search.save

      redirect_to :action => "user_result", :id => search.id
    else
      cookies[:general] = params[:query][:keyword]
	    cookies[:entities] = params[:query][:entities]
      cookies[:count] = params[:query][:count]
      cookies[:result_type] = params[:query][:result_type]
      cookies[:until] = Date.strptime(params[:query][:search_date], '%m/%d/%Y').strftime("%Y-%m-%d")

      redirect_to :action => "result"

    end
  end

  def result
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "E58XYQmJzwu03GJ8o3YGDbQJu"
      config.consumer_secret     = "qrhRkdp7IMg7ZdDKibFjkxGTFWe11HhHx0aupEAnSCN7KoIXqI"
      config.access_token        = "2512534718-1dHuDxdtZphrkoKA8TJqAsvoc23kxBhRmXJ42BF"
      config.access_token_secret = "5wnW2BhxjPLWYefCSVsvqdfRYKewuSHsZEZhaB7drJ2zF"
    end
	if cookies[:entities]
		if cookies[:result_type]
			@tweets = client.search(cookies[:general], :lang => "en", :include_entities => true, :result_type => cookies[:result_type]).take(cookies[:count].to_i)
		else
			@tweets = client.search(cookies[:general], :lang => "en", :until => cookies[:until]).take(cookies[:count].to_i)
		end
	else
		if cookies[:result_type]
			@tweets = client.search(cookies[:general], :lang => "en", :result_type => cookies[:result_type]).take(cookies[:count].to_i)
		else
			@tweets = client.search(cookies[:general], :lang => "en", :until => cookies[:until]).take(cookies[:count].to_i)
		end
	end
		
	  #@tweets = client.search(cookies[:general], :since=> => cookies[:since], :include_entities=>cookies[:entities], :count=>cookies[:num_results].to_i)
    #@tweets = client.search(cookies[:general], :lang => "en", :result_type => cookies[:result_type]).take(cookies[:count].to_i)
  end

  def user_result
    @query = Query.find(params[:id])
    client = Twitter::REST::Client.new do |config|
      config.consumer_key        = "E58XYQmJzwu03GJ8o3YGDbQJu"
      config.consumer_secret     = "qrhRkdp7IMg7ZdDKibFjkxGTFWe11HhHx0aupEAnSCN7KoIXqI"
      config.access_token        = "2512534718-1dHuDxdtZphrkoKA8TJqAsvoc23kxBhRmXJ42BF"
      config.access_token_secret = "5wnW2BhxjPLWYefCSVsvqdfRYKewuSHsZEZhaB7drJ2zF"
    end
    if !@query.search_date.empty?
      # until is currently not working going back to default
      # @tweets = client.search(@query.search_query, :lang => "en", :since => @query.search_date, :until => @query.search_date, :result_type => @query.query_type).take(@query.search_limit)
      @tweets = client.search(@query.search_query, :lang => "en", :result_type => @query.query_type).take(@query.search_limit)
    else
      @tweets = client.search(@query.search_query, :lang => "en", :result_type => @query.query_type).take(@query.search_limit)
    end
    render 'result'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/_content.html.erb
<div class="container-fluid content">
  <% if notice.present? %>
      <p class="warning"><%= notice %></p>
  <% end %>
  <% if alert.present? %>
      <p class="alert warning"><%= alert %></p>
  <% end %>

  <%= yield %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer navbar-static-bottom navbar-default">
      <div class="col-xs-2 col-md-2">
      </div>
      <div class="col-xs-8 col-md-8">
        <div class="nav navbar-nav navbar-text navbar-right">
          Twitter Query Engine Copyright <%= Time.now.year %>
        </div>
      </div>
      <div class="col-xs-2 col-md-2 ">
      </div>
</footer>

app/views/layouts/_header.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="col-xs-2 col-md-2"></div>
  <div class="container col-xs-8 col-md-8">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand">Twitter Query Engine</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Search",   main_search_path %></li>
        <li><%= link_to "Manage Account",   main_admin_path %></li>
      </ul>
      <div class="nav navbar-nav navbar-text navbar-right" style="padding: 0px 15px">
        <%= render 'layouts/user_widget' %>
      </div>
    </div><!--/.nav-collapse -->
  </div>
  <div class="col-xs-2 col-md-2"></div>
</nav>

app/views/layouts/_tweets.html.erb
<section id="tweets">
  <ul>
    <% @tweets.each do |tweet| %>
        <li><%= link_to tweet.text, "https://www.twitter.com/#{tweet.user.screen_name}" %></li>
    <% end %>
  </ul>
</section>

app/views/layouts/_user_widget.erb
<% if user_signed_in? %>
    Welcome <%= current_user.email %>
    <%= link_to 'Logout', destroy_user_session_path, :method => :delete, class: 'btn-xs btn-danger' %>
    <%= link_to 'Admin', main_admin_path, class: 'btn-xs btn-primary' %>
<% else %>
    You are not signed in.
    <%= link_to 'Login', new_user_session_path, class: 'btn-xs btn-success' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="page-container" class="container-fluid">

  <%= render "layouts/header" %>

  <div id="content-container" class="row">
    <!-- Left sidebar -->
    <div id="left-container" class="col-xs-2 col-md-2 sidebar"></div>

    <!-- content-->
    <div id="content" class="col-xs-8 col-md-8">

      <!-- content section -->
      <%= render "layouts/content" %>

    </div>

    <!-- right sidebar-->
    <div id="right-container" class="col-xs-2 col-md-2 sidebar container-fluid"></div>



  </div>  <!-- end of content-container -->

  <!-- footer -->
  <%= render "layouts/footer" %>

</div><!-- end of page-container -->
</body>
</html>

app/views/main/_form.html.erb
<%= form_for :query, :url=>{:action=>"query"} do |f| %>
    
        General Search: <%= f.text_field(:keyword) %> <br />
		<%= label_tag(:entities, "Return entities?") %>
        <%= f.check_box(:entities) %> <br />
        Number of Results: <%= f.text_field(:count) %> <br />
        (Max 100) <br />
        Result Type: <%= f.select :result_type, [['Recent','recent'],['Mixed','mixed'],['Popular','popular']] %>
            <p> * mixed: Include both popular and real time results in the response.<br />
              * recent: return only the most recent results in the response<br />
              * popular: return only the most popular results in the response.</p><br />
        Return results until: <%= f.text_field(:search_date, "data-provide" => 'datepicker', 'data-date-autoclose' => 'true',) %> <br /><br />

		<%= submit_tag "Search"%>
<% end %>

app/views/main/admin.html.erb
<% content_for :title do %>Admin<% end %>
<ul>
  <li><%= link_to "Change your password", edit_user_registration_path %></li>
</ul>


<footer>
  <div class="col-md-2 text-center">
    <%= link_to 'Home', root_path, class: 'btn-sm btn-primary' %>
  </div>
</footer>

app/views/main/index.html.erb
<% content_for :title do %>Home<% end %>

<h1>Welcome
  <% if user_signed_in? %>
   <%= current_user.email %>
  <% end %>
</h1>

  <% if !@last.nil? %>
    <p>
  Below is your last five seach words:
      </p>
    <table id="result-table" class="table" width="100%">
      <thead>
      <tr>
        <th>Search Word(s)</th>
        <th>Search Limit</th>
        <th>Query Type</th>
        <th>Search Date</th>
        <th>Created</th>
      </tr>
      </thead>
      <tbody>
      <% @last.each do |last| %>
          <tr>
            <td><%= link_to last.search_query, main_user_result_path(:id => last.id) %></td>
            <td><%= last.search_limit %></td>
            <td><%= last.query_type %></td>
            <td><%= last.search_date %></td>
            <td><%= DateTime.parse(last.created_at).in_time_zone("Eastern Time (US & Canada)").strftime("%m/%d/%y at %I:%M %p") %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
    <div class="clear"></div>

    <script type="text/javascript">
        $(document).ready(function() {

            $('#result-table').DataTable({
                "bJQueryUI": true,
                "bAutoWidth": true,
                "bAutoHeight": false,
                "bFilter": false,
                "bLengthChange": false,
                "length": 5,
                "iDisplayLength": 5,
                "bInfo": false,
                "bPaginate": false,
                "aoColumns": [
                    { "sSortDataType": "dom-text"},
                    { "sSortDataType": "dom-text"},
                    { "sSortDataType": "dom-text"},
                    { "sSortDataType": "dom-text"},
                    { "sSortDataType": "dom-text"}
                ]
            });

        });
    </script>
  <% end %>
<br /><br />
Click <%= link_to 'New Search', main_search_path, class: 'btn-xs btn-success' %> to start a new twitter feed.
<% if !user_signed_in? %>
    Or log in  to go to your account.
<% end %>

app/views/main/result.html.erb
<% content_for :title do %>Results<% end %>

<% if user_signed_in?
     keyword = @query.search_query
   else
     keyword = "#{cookies[:general]}"
   end %>

<h1>Result Page</h1>
<br />
<p>
  This is the result of your query. You searched for the word(s): <em><%= keyword %></em>
</p>

<table id="result-table" class="table" width="100%">
  <thead>
  <tr>
    <th>Tweets</th>
    <th>Username</th>
    <th>Posted On</th>
  </tr>
  </thead>
  <tbody>
    <% @tweets.each do |tweet| %>
      <% time = DateTime.parse("#{tweet.created_at}") %>
      <tr>
        <td><%= "#{tweet.text}" %></td>
        <td><%= link_to "#{tweet.user.screen_name}", "https://www.twitter.com/#{tweet.user.screen_name}" %></td>
        <td><%= time.in_time_zone("Eastern Time (US & Canada)").strftime("%m/%d/%y at %I:%M %p") %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="clear"></div>

<script type="text/javascript">
$(document).ready(function() {

    $('#result-table').DataTable({
        "bJQueryUI": true,
        "bAutoWidth": true,
        "bAutoHeight": false,
        "bFilter": false,
        "bLengthChange": false,
        "length": 5,
        "iDisplayLength": 5,
        "bInfo": true,
        "aoColumns": [
            { "sSortDataType": "dom-text"},
            { "sSortDataType": "dom-text"},
            { "sSortDataType": "dom-text"}
        ]
    });

});
</script>

app/views/main/search.html.erb
<% content_for :title do %>Search<% end %>
<h1>Search</h1>
<p>
  Welcome to the Twitter Query Engine. Here is where you enter your search to
  start crawling through Twitter. Select the type of search you would like to
  conduct, and then enter your query.
</p>

<%= render 'form' %>